version: "3.7"

services:
  sql-server-db-s:
    container_name: sql-server-db-s
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"